### ISSUE TITLE
sentry-debug-meta.properties file was not found

### ISSUE THREAD

**Issue by 15matias15** [getsentry/sentry-react-native#1053]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.2

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
          dsn: CONSTANTS.sentry_dsn,
        });
```
---
**I have following issue:**
After I integrate sentry I tried to log the test error `"My first Sentry error!"`, but nothing it's logged on sentry, here're the logs from logcat.

```
2020-09-03 14:54:19.027 16181-16181/? D/Sentry: Auto-init: false
2020-09-03 14:54:19.027 16181-16181/? I/Sentry: Retrieving auto-init from AndroidManifest.xml
2020-09-03 14:54:19.094 16181-16181/? D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libsentry-android.so: deferring to libdir
2020-09-03 14:54:19.094 16181-16181/? D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libsentry.so: deferring to libdir
2020-09-03 14:54:19.644 16181-16297/? I/react-native-sentry: Starting with DSN: *MYDSN*
2020-09-03 14:54:19.644 16181-16297/? I/react-native-sentry: Native Integrations '[io.sentry.core.UncaughtExceptionHandlerIntegration@cad10c6, io.sentry.core.ShutdownHookIntegration@ff0a887, io.sentry.core.SendCachedEventFireAndForgetIntegration@c3b13b4, io.sentry.core.SendCachedEventFireAndForgetIntegration@6606bdd, io.sentry.android.core.NdkIntegration@1d97352, io.sentry.android.core.EnvelopeFileObserverIntegration$OutboxEnvelopeFileObserverIntegration@e254623, io.sentry.core.SendCachedEventFireAndForgetIntegration@34fb720, io.sentry.android.core.AnrIntegration@57ce8d9, io.sentry.android.core.AppLifecycleIntegration@5f7729e, io.sentry.android.core.ActivityBreadcrumbsIntegration@37c217f, io.sentry.android.core.AppComponentsBreadcrumbsIntegration@549254c, io.sentry.android.core.SystemEventsBreadcrumbsIntegration@e4a3995, io.sentry.android.core.TempSensorBreadcrumbsIntegration@1641aaa, io.sentry.android.core.PhoneStateBreadcrumbsIntegration@13b569b]'
2020-09-03 14:54:19.646 16181-16334/? I/Sentry: sentry-debug-meta.properties file was not found.
2020-09-03 14:54:19.651 16181-16334/? D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at io.sentry.android.core.util.RootChecker.checkSUExist(Unknown Source:12)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(Unknown Source:12)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(Unknown Source:18)
        at io.sentry.android.core.DefaultAndroidEventProcessor.a(Unknown Source:0)
        at zg7.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(Unknown Source:12) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(Unknown Source:12) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(Unknown Source:18) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.a(Unknown Source:0) 
        at zg7.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

[Actual result]

**Expected result:**

See the `"My first Sentry error!"` Error

**Comment by jennmueng** [comment]
Do you have a `sentry.properties` file in your repo? In the android case, it should be under `./android`

**Comment by 15matias15** [comment]
@jennmueng yes, it's inside `./android`
```
defaults.url=XX
defaults.org=XXX
defaults.project=XXX
auth.token=XXX
```

**Comment by jennmueng** [comment]
Hmm otherwise the errors looks like something @marandaneto would be able to tell.

**Comment by marandaneto** [comment]
the stack traces on the description are just fine, it's DEBUG and INFO levels, they are not bugs.

it's probably something else, have you used the sentry-wizard as the docs mention to install Sentry properly? cc @15matias15

**Comment by 15matias15** [comment]
Hi @marandaneto 
Yes, I run sentry-wizard, now I'm getting this `2020-09-15 10:44:46.137 19791-19901/? E/ReactNativeJS: Error: My first Sentry error!` on Logcat, but nothing on sentry dashboard

**Comment by jennmueng** [comment]
@15matias15 can you pass `debug: true` to the call to `Sentry.init({ ... })` in your JS code and paste the console logs (from the React Native dev server) for us to see?

**Comment by 15matias15** [comment]
@jennmueng This it's what I get on RN terminal
```
[Wed Sep 16 2020 14:47:22.505]  LOG      Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
[Wed Sep 16 2020 14:47:22.506]  LOG      Sentry Logger [Log]: Integration installed: Release
[Wed Sep 16 2020 14:47:22.506]  LOG      Sentry Logger [Log]: Integration installed: InboundFilters
[Wed Sep 16 2020 14:47:22.507]  LOG      Sentry Logger [Log]: Integration installed: FunctionToString
[Wed Sep 16 2020 14:47:22.507]  LOG      Sentry Logger [Log]: Integration installed: Breadcrumbs
[Wed Sep 16 2020 14:47:22.507]  LOG      Sentry Logger [Log]: Integration installed: LinkedErrors
[Wed Sep 16 2020 14:47:22.508]  LOG      Sentry Logger [Log]: Integration installed: UserAgent
[Wed Sep 16 2020 14:47:22.508]  LOG      Sentry Logger [Log]: Integration installed: DebugSymbolicator
[Wed Sep 16 2020 14:47:22.508]  LOG      Sentry Logger [Log]: Integration installed: RewriteFrames
[Wed Sep 16 2020 14:47:22.509]  LOG      Sentry Logger [Log]: Integration installed: DeviceContext
```

**Comment by 15matias15** [comment]
@jennmueng I move the throw error to another view, and now I'm getting this `Sentry Logger [Log]: Failed to get device context from native: TypeError: undefined is not a function`

**Comment by 15matias15** [comment]
@jennmueng It's working now, there was an old `ErrorBoundary` wrapper, that was catching the errors and send them to other service. Thanks, I'll close this issue
