### ISSUE TITLE
Release 2.2 (GA Performance with auto instrumentation)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#1272]
This issue will track the release of v2.2 with auto instrumentation of React Navigation v4, v5, fetch/xhr and react profiler.

- [x] Merged the JS blocking PR: https://github.com/getsentry/sentry-javascript/pull/3144
- [x] Update master with the latest JavaScript SDK.
- [x] Investigate a way to handle blank navigation transactions
- [x] Get a Docs Draft PR ready for auto instrumentation, early so @pelowriter have a chance to review it.
- [x] Merged the main PR with integrations #1230
- [x] Review the manual API docs - Make sure they are up to date with API and behavior
- [x] Merge auto instrumentation API.
- [x] `craft publish`
- [ ] Wait for Android device context #1291
- [X] Migrate to using `beforeNavigate` #1313
- [X] Fix issue regarding the initial transaction on app start #1315 
- [ ] Document updated `beforeNavigate` 
- [ ] Prepare wizard PR for the docs (will be merged N days after GA)
- [X] Merge Context updating methods from JS: https://github.com/getsentry/sentry-javascript/pull/3192

**Comment by marandaneto** [comment]
I'd say we could go ahead without https://github.com/getsentry/sentry-react-native/issues/1291 and iterate later

**Comment by marandaneto** [comment]
@jennmueng mind explaining what's the issue with the `beforeNavigate`? not sure what this is about

**Comment by jennmueng** [comment]
@marandaneto `beforeNavigate` (to be passed to the `ReactNativeTracing` integration)  currently wasn't used in RN due to the limitation with the V5 instrumentation but I found a workaround that allows it to be used. This way we match the API on JS and get rid of the redundant `shouldSendTransaction` option passed to the instrumentation.

**Comment by marandaneto** [comment]
@jennmueng cool thanks, should we create its own issue for that. so we could track it down and link to the PR? this also would require docs?

**Comment by PeloWriter** [comment]
Yes, please, on the Docs. Here's the WIP for Performance Docs - https://github.com/getsentry/sentry-docs/pull/2970

**Comment by marandaneto** [comment]
> @jennmueng cool thanks, should we create its own issue for that. so we could track it down and link to the PR? this also would require docs?

@jennmueng I guess this issue is ready to be closed, do we need to update docs?

**Comment by jennmueng** [comment]
@marandaneto Yes we need docs

**Comment by marandaneto** [comment]
> @marandaneto Yes we need docs

ok now we have its own issue for docs https://github.com/getsentry/sentry-docs/issues/2995
