### ISSUE TITLE
Add support for Source Maps Debug ID in Hermes bundle

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2947]
### Description

Based on the initial testing, the current way of injecting Debug ID into a bundle file works only for plain text JS files.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cli/pull/1667
- [ ] https://github.com/getsentry/sentry-react-native/pull/3164
- [ ] https://github.com/getsentry/sentry-react-native/issues/2892
- [ ] https://github.com/getsentry/sentry-react-native/pull/2900
``` 

Debug ID must be propagated to Hermes Combined Source Map, but CLI at the moment doesn't automatically upload combined source maps.

```[tasklist]
### Related tasks
- [ ] https://github.com/getsentry/sentry-cli/issues/1569
```

**Comment by marandaneto** [comment]
@krystofwoldrich you can link it to https://github.com/getsentry/team-mobile/issues/133

**Comment by krystofwoldrich** [comment]
We might be able to use `getPolyfills` to add the debug id holder object to the JS runtime 

https://facebook.github.io/metro/docs/configuration#getpolyfills

**Comment by shanamatthews** [comment]
Hey @krystofwoldrich - I know we have docs on [uploading source maps with Hermes](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/), are there any updates needed based on these improvements?

**Comment by krystofwoldrich** [comment]
- Follow up https://github.com/getsentry/sentry-react-native/issues/3326
