### ISSUE TITLE
React Native Mixed Stack Traces Support 

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3125]
### Description

This is an umbrella issue for all issues and PRs related to the work on supporting mixed stack traces in React Native.

```[tasklist]
### MVP
- [ ] https://github.com/getsentry/sentry-react-native/pull/3201
- [x] https://github.com/reactwg/react-native-new-architecture/discussions/122
- [ ] https://github.com/facebook/react-native/pull/36729
- [ ] https://github.com/facebook/react-native/pull/36925
- [ ] https://github.com/facebookincubator/fbjni/pull/78
- [ ] https://github.com/facebook/react-native/pull/37879
```

```[tasklist]
### Todo In SDK Repository
- [ ] https://github.com/getsentry/sentry-react-native/issues/3257
```

```[tasklist]
### Todo In RN Repository
- [ ] https://github.com/facebook/react-native/pull/37484
- [ ] Add native stack trace to the RedBox UI (React Native Errro dev UI)
```

[Internal notion page.](https://www.notion.so/sentry/RNNA-crashes-coop-aa38ebcb554f4f418183463b86da681a)

**Comment by shanamatthews** [comment]
Hey @krystofwoldrich - would this improvement need any docs updates? Like, will there be any steps users need to take to make sure this works, or troubleshooting?

**Comment by krystofwoldrich** [comment]
@shanamatthews From https://github.com/getsentry/sentry-react-native/releases/tag/5.9.0 onwards if users use RN version that supports this, it works by default. To make users more aware of the feature it would make sense to add some small entry about what version of RN to use.

**Comment by krystofwoldrich** [comment]
Rejected Promise Mixed Stack Trace first released in RN https://github.com/facebook/react-native/releases/tag/v0.74.0 (https://github.com/facebook/react-native/commit/7612e6601a1c402c548dfe2fe548b1c481659993)

Mixed Stack Traces for sync native functions first released in https://github.com/facebook/react-native/releases/tag/v0.73.0 (https://github.com/facebook/react-native/commit/f05d202813a1abeba58365ae492a623429702609)
