### ISSUE TITLE
Tracing without Performance

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-react-native#3166]
See Project: https://github.com/getsentry/team-sdks/issues/5
See Project Board: [github.com/orgs/getsentry/projects/110](https://github.com/orgs/getsentry/projects/110)

Note: implementation details/requirements for Mobile (vs. backend) SDKs TBD. PR for Java can act as reference: https://github.com/getsentry/sentry-java/pull/2788

```[tasklist]
### Tasks
- [x] Verify JS implementation work with RN
- [ ] If needed re-export new helper functions to continue trace
- [x] Add documentation/reuse JS docs
```

**Comment by krystofwoldrich** [comment]
This task doesn't require implementation changes in the RN SDK, as the logic lives in JS SDK.
