### ISSUE TITLE
Sentry React Native + OpenTelemetry

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3180]
### Description

- Related to https://github.com/getsentry/sentry/discussions/40712#discussioncomment-5860166

Based on the POC we did, creating spans using Otels' API and Sentry Spans Processor works well in RN apps. We just need to release platform agnostic JS package and document the steps.

```[tasklist]
### Tasks
- [ ] Create platform agnostic `@sentry/opentelemetry` (based on the current `@sentry/opentelemetry-node`)
- [ ] Finish sample in the app https://github.com/getsentry/sentry-react-native/pull/2979
- [ ] Add at least integrations tests, maybe e2e to ensure this won't break in the future as the implementation of the span processor will live in the JS SDK repo
- [ ] Update docs
```
