### ISSUE TITLE
Multiple tracking.enable$argument_0.onUnhandled error reported

### ISSUE THREAD

**Issue by elmotan95** [getsentry/sentry-react-native#3185]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.5.0

**`react-native` version:** 0.69.10

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn: 'redacted',
    enableAutoSessionTracking: true,
    environment: config.environment,

    ignoreErrors: [
      // Axios throw error from createError.js, please see useFetch for error log
      /Request\sfailed\swith\sstatus\scode.*/,
      // react-native-fingerprint-scanner
      /.*biometric.*/,
      // appsflyer
      /.*inapps\.appsflyer\.com.*/,
      /.*com\.appsflyer\.sdk\.network.*/,
    ],

    integrations: [
      new Sentry.ReactNativeTracing({
        enableUserInteractionTracing: true,
        routingInstrumentation,
        shouldCreateSpanForRequest: url => {
          const urlRedacted = /redacted/;
          const urlLocalhost = /localhost/;

          return !url.match(urlRedacted) && !url.match(urlLocalhost);
        },
        // ... other options
      }),
    ],

    sampleRate: 0.2,
    // Sessions close after app is 10 seconds in the background.
    sessionTrackingIntervalMillis: 10000,
    tracesSampleRate: 0.2,
  });
```

---
**I have following issue:**

[Description]

I saw issue being logged on Sentry that related to error reporting. Not sure what caused this issues.

```
tracking.enable$argument_0.onUnhandled


```

<img width="1184" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/36393703/d7c6f876-04c5-4d3f-9af4-02d43835a374">

**Actual result:**

[Actual result]

**Expected result:**

No issues related to sentry reported

**Comment by isinuyk** [comment]
@krystofwoldrich @elmotan95 
Got the same problem on the newly released version of the app. 
For me, it is IOS only.

<div><img src="https://github.com/getsentry/sentry-react-native/assets/72970722/e5862dc5-6255-4b04-9a63-76d7e5f7386c" width="400" height="400"/></div>
<div><img src="https://github.com/getsentry/sentry-react-native/assets/72970722/2b67aa98-0275-4cd6-8a48-6089c2b1d747" width="400" height="400"/></div>

 "@sentry/react-native": "^5.4.1",
 "react-native": "0.71.7",

**Comment by krystofwoldrich** [comment]
@isinuyk Thank you for the information, are you able to reproduce it locally, from the message I assume not, but I want to double-check?

**Comment by elmotan95** [comment]
> Hi, thank you for the message, could you share more about the error, are there any breadcrumbs, are there more frames in the stack trace?

Nope. Data form breadcrumbs does not provide any relevant information (it's only API call with status 200 and screen name). And it does not happened on development apps.

**Comment by krystofwoldrich** [comment]
@isinuyk Since you mentioned it's iOS only, could it be incorrect source maps causing the issue, are your other iOS JS errors source mapped correctly?

**Comment by isinuyk** [comment]
> @isinuyk Since you mentioned it's iOS only, could it be incorrect source maps causing the issue, are your other iOS JS errors source mapped correctly?

I don't think so. It is an example of another issue within the same release which has the correct source map
<div><img src="https://github.com/getsentry/sentry-react-native/assets/72970722/4c8bf03b-3f49-4454-8fce-9a0dfafdf58f" width=250/></div>

**Comment by NiharR27** [comment]
+1

**Comment by NiharR27** [comment]
> @NiharR27 Thank you for the information, would you be able to narrow it down? Or share a minimal reproducible example?

@krystofwoldrich sure, i will try to replicate once I get to the office tomorrow.

**Comment by NiharR27** [comment]
Still trying to replicate this on release build (when building on my local device).
Here is sentry log however:

![Screenshot 2023-08-30 at 10 14 25 am](https://github.com/getsentry/sentry-react-native/assets/52943748/e08bbfdc-106e-4058-9c8d-dc2faf4ffa4c)

![Screenshot 2023-08-30 at 10 14 45 am](https://github.com/getsentry/sentry-react-native/assets/52943748/46cb61d1-6327-4a97-b8c1-e5a8cd28a5a1)

Note: I have hermes enabled.

It seems to be happening on iOS devices as well. I will post something in this post, in-case i find more / able to replicate

**Comment by isinuyk** [comment]
The interesting thing is that right after I made a codepush to the affected by this problem latest IOS release the title and traces for this issue changed a bit. Now it looks like:
<div><img src="https://github.com/getsentry/sentry-react-native/assets/72970722/e5cec129-96cb-4d8b-85c0-a8e426fbe5c9" width=250/></div>

**Comment by Bardiamist** [comment]
Same problem, 4 users, 5 events
```
Error: [{}]
  at tracking.enable$argument_0.onUnhandled(node_modules/@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers.js:85:57)
  at onUnhandled(node_modules/promise/setimmediate/rejection-tracking.js:73:25)
  at apply(native)
  at setTimeout(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:213:35)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:113:15)
  at callTimers(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:359:30)
  at apply(native)
  at __callFunction(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:428:32)
  at __guard$argument_0(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:43)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:367:7)
  at callFunctionReturnFlushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:18)
  ```

**Comment by krystofwoldrich** [comment]
@ts-ign0re Thanks for the info, were you able to reproduce it locally?

**Comment by MarkHaakman** [comment]
For me it also happens on Android. 
8 users with 291 events. RN 0.71.13, Sentry 5.9.1.
I could not reproduce it locally.

**Comment by brookslyrette** [comment]
Also happening to us. 400+ reports a day, breadcrumbs show only 200 and nothing indicative of an error.

**Comment by krystofwoldrich** [comment]
@brookslyrette Thanks for the message, are your other errors in Sentry symbolicated correctly? We suspect this is caused by incorrect symbolication.

**Comment by Bardiamist** [comment]
>Thanks for the message, are your other errors in Sentry symbolicated correctly?

Recently I receiving from time to time not readable `SIGABRT` errors. But some error still readable.

<details><summary>Example</summary>

```
OS Version: Android 7.1.1 (ONEPLUS A5000_23_171031)
Report Version: 104

Exception Type: Unknown (SIGABRT)

Application Specific Information:
Abort

Thread 0 Crashed:
0   [vdso]                          0xcdfbed91          __kernel_vsyscall
1   libc.so                         0xc95f623c          tgkill
2   libc.so                         0xc95f1a15          pthread_kill
3   libc.so                         0xc95a2a7a          raise
4   libc.so                         0xc9599ee6          abort
5   libstagefright.so               0xcc0e691c          android::MPEG4Writer::Track::getStartTimeOffsetScaledTime
6   libstagefright.so               0xcc0e4e96          android::MPEG4Writer::Track::writeSttsBox
7   libstagefright.so               0xcc0e4386          android::MPEG4Writer::Track::writeStblBox
8   libstagefright.so               0xcc0dbb8a          android::MPEG4Writer::Track::writeTrackHeader
9   libstagefright.so               0xcc0dae51          android::MPEG4Writer::writeMoovBox
10  libstagefright.so               0xcc0d8c19          android::MPEG4Writer::reset
11  libstagefright.so               0xcc0e7d30          android::MPEG4Writer::stop
12  libstagefright.so               0xcc11078f          android::MediaMuxer::stop
13  libmedia_jni.so                 0xbd7d763f          <unknown> + 3179116095
14  system@framework@boot-framework.oat0x72f5dfbe          oatexec
```

</details>

**Comment by Kowaio** [comment]
Hello,

Just to make my contribution, we see this from quite some weeks now in our release app too. I never succeeded to reproduce this in local / debug mode. At first we thought it was a symbolication error and I contacted Sentry support. We fixed some details with them, mostly on how to generate and upload symbol maps properly, but it still happens in our new release while other errors are now correctly symbolicated.

Happens on both iOS and Android.

I don't have more to share unfortunately and I don't know where to look at to try and fix those errors, if there are even real issues.

Some screenshots for details below, thanks !

![1](https://github.com/getsentry/sentry-react-native/assets/7236237/0c7a1374-e216-450c-9270-f18225818ec9)
![2](https://github.com/getsentry/sentry-react-native/assets/7236237/b5e092d9-360e-4fbb-8971-2c8ba83474c2)
![3](https://github.com/getsentry/sentry-react-native/assets/7236237/ee25ac57-6242-489b-91b9-c5662bf06ad4)

**Comment by krystofwoldrich** [comment]
@Kowaio Thank you for the information, we will keep you posted on any updates regarding this issue.

**Comment by lucasftcruz** [comment]
Facing the same issue on iOS. For us started coincidentally when we updated RN `0.70.9` to `0.70.13`. I'm not able to reproduce the issue and can confirm it only happens on `release` builds

`"react-native": "^0.71.14",`
`"@sentry/react-native": "^5.4.0",`

![Screenshot 2023-11-08 at 2 17 36 PM](https://github.com/getsentry/sentry-react-native/assets/36747663/cba20f0c-91bd-44b8-921c-7cdd2b4d4cc7)

**Comment by krystofwoldrich** [comment]
@lucasftcruz The stack trace you shared looks correct, you can ignore the first frame pointing to Sentry, that's present because we report the unhandled Promise rejection.

**Comment by savv** [comment]
We are also seeing this error on iOS right after Codepush installs a bundle and it causes the app to crash. We can replicate this ~50% of the time on one of our devices by a) freshly installing the app b) selecting "Install" on the Codepush prompt*. Skipping b) means that the app does not crash. I am not sure if this is caused by Sentry, but I thought I would report my findings.

The stack trace, which similar to the above seems to start here:
1. in [callFunctionReturnFlushedQueue](https://github.com/facebook/react-native/blob/fa89dd68b0f64acb68c45912d39fe9beed4e13cf/packages/react-native/Libraries/BatchedBridge/MessageQueue.js#L112)
2. Then this [invariant](https://github.com/facebook/react-native/blob/fa89dd68b0f64acb68c45912d39fe9beed4e13cf/packages/react-native/Libraries/BatchedBridge/MessageQueue.js#L428) seems to trigger in line 428: `Failed to call into JavaScript module method ${module}.${method}(). Module exists, but the method is undefined.`
This would further suggest that it's related to Codepush. For example, Codepush invalidates all RCTBridges when it restarts (which happens when a new bundle is installed.)

The one thing that doesn't fit the above, is that I don't see this error message anywhere. Maybe `invariant` is not creating the error in a way that is compatible with sentry. Maybe "Error: 1" comes from [here](https://github.com/zertosh/invariant/blob/master/invariant.js#L46)?

<img width="838" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/747519/92af2dc2-a450-48c7-9399-3b57eb2f526e">

* Our codepush config checks for updates when the app starts, and asks the user whether they want to upgrade; if you press "Install", we install the new bundle immediately. Config: `{checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, installMode: codePush.InstallMode.IMMEDIATE,updateDialog: {}}`

**Comment by krystofwoldrich** [comment]
@savv Thank you for the detailed findings.

**Comment by savv** [comment]
> @savv Thank you for the detailed findings.

[reactnativeerrorhandlers.ts](https://github.com/getsentry/sentry-react-native/blob/master/src/js/integrations/reactnativeerrorhandlers.ts) seems to polyfill Promises, in order to catch unhandled promise rejections, but I wasn't able to trigger that code. 

When does [onUnhandled](https://github.com/getsentry/sentry-react-native/blob/master/src/js/integrations/reactnativeerrorhandlers.ts#L77) ever execute? How can I get it to?

**Comment by krystofwoldrich** [comment]
The `onUnhandled` get triggered on unhandled promise rejection. 

The SDK reports that there was unhandled rejected promise, but the top of the stack should exclude the Sentry frame.

**Comment by savv** [comment]
> The `onUnhandled` get triggered on unhandled promise rejection.
> 
> The SDK reports that there was unhandled rejected promise, but the top of the stack should exclude the Sentry frame.

I see, so as `invariant` sets `error.framesToPop = 1;` maybe there's a bug in `addGlobalEventProcessor` / [parseErrorStack](https://github.com/getsentry/sentry-react-native/blob/e9fea859dc0f2d7405080380d23657d9fa6aa6b7/src/js/integrations/debugsymbolicator.ts#L57C13-L57C28) or it's incompatible with Sentry's promise handling. Although I wasn't able to replicate it.

**Comment by krystofwoldrich** [comment]
@savv Thank you, we'll investigate it.

**Comment by savv** [comment]
As a final FYI, I also just saw that RN 0.72.7 includes the following fix:

Show correct stack frame on unhandled promise rejections on development mode.
https://github.com/facebook/react-native/commit/18c9797ecc8dab220ec68aae011ddb73db17a99d

While I didn't look at the code it could be related. Thanks again

**Comment by birgernass** [comment]
@savv were you able to get to the bottom of the `Error: 1` issue? We see these events very frequently since upgrading to 5.15.x from a 5 alpha version.

**Comment by rodolfoBee** [comment]
Reopening issue as users are getting these reports in the newest versions of the SDK. The issue does not seem to be caused by the SDK, it is simply being reported by it. 

@krystofwoldrich can you please confirm it from the Mobile SDK team side?

**Comment by ts-ign0re** [comment]
If you encounter this problem, try to find the following line in your code or in the code of the libraries you use

`js
   return Promise.reject();
`

my case was due to the similar use of Promise, which caused onUnhandled

**Comment by krystofwoldrich** [comment]
@rodolfoBee I can confirm, this is not an issue caused by the SDK. The SDK just captures a Promise rejection without any additional information, without a stack trace attached.

This can happen for example when `Promise.reject()` is called without an `error` instance. Like @ts-ign0re mentioned.
