### ISSUE TITLE
App Hang tracking not working

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-react-native#3460]
**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 
5.15.1

**`react-native` version:** 
0.72.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise
**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'MY_DSN',
  debug:true
})
```
---
**I have the following issue:**

A user reported the app hanging but not event was sent to Sentry. As per docs:

> There are many reasons why an app may become unresponsive, such as long-running code, infinite loop bugs, and so on. With app hang tracking you can detect and fix them.

I created an infinite loop to test it and no app hang events were sent. The same infinite loop works fine with Cocoa SDK.

**Steps to reproduce:**
- Create a base react-native app
- Add Sentry to it
- Add the following button anywhere:
```
<Button
     onPress={() => {
         var i = 1;
          while (i > 0){i++;}
      }}
      title="LeLoop"
      color="#841584"
  />
```
- run the app on ios

It is still possible to scroll through the app, but all other buttons no longer work as the app is still on the loop. But no event is sent.

Under which conditions is it expected for an event to be sent?

**Comment by yogendrajs** [comment]
Based on our recent conversations, thanks for taking the time to create the issue here, Rodolfo. Will subscribe and follow up on this.

**Comment by krystofwoldrich** [comment]
@rodolfoBee and @yogendrajs Thank you for the message. 

The SDK currently reports [App Hangs](https://docs.sentry.io/platforms/react-native/configuration/app-hangs/) when the native UI thread hangs (users can't interact with the app, even scrolling doesn't work). 

The [JS loop hangs (stalls)](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#stall-tracking) are currently reported as a metric with Sentry Transactions.

 I've marked this issue as a feature request we will discuss internally if and how to report JS Loop stalls as Errors.

**Comment by yogendrajs** [comment]
@krystofwoldrich understood, thanks. We've also used the React Native Tracing option within the Performance, but having trouble understanding how this metric will be recorded in the dashboard. Can you provide a screenshot or a sample metric displaying the same? Thanks

**Comment by krystofwoldrich** [comment]
When you open [Transaction Detail](https://docs.sentry.io/product/sentry-basics/concepts/tracing/event-detail/) you will see the stalls on the right side. [Transactions are created based on screen names defined in navigation library you use.](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/)

Stall times are displayed in milliseconds.

![Screenshot 2023-12-13 at 16 58 29](https://github.com/getsentry/sentry-react-native/assets/31292499/31be388d-3571-429d-8a00-89e3448af2e2)

**Comment by yogendrajs** [comment]
Okay, all the stall-related numbers are always zero for me, it seems like it is because we don't use any of the mentioned navigation libraries directly.
