### ISSUE TITLE
Send list of libraries loaded during app start

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-react-native#3520]
### Description

See https://github.com/getsentry/team-mobile/issues/165.

```[tasklist]
### Tasks
- [ ] Retrieve native libs debug meta
- [ ] Can we detect what native libs are system/RN framework?
- [ ] Do native debug meta include/how to track RN JS Native Modules?
```
