### ISSUE TITLE
W3C Trace Context support

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3564]
### Description

- Meta issue https://github.com/getsentry/team-sdks/issues/41

Tracing headers are implemented in the JS SDK. When JS implements the new headers we have to bump the JS SDK version, add the new options to enable W3C Trace Context headers and update the sample app.

```[tasklist]
### Tasks
- [ ] Bump JS SDK to version supporting W3C
- [ ] Add option to enable W3C/Sentry headers
- [ ] Verify `sentry-trace` and `trace-parent` can be send in parallel
- [ ] Verify incoming `trace-parent` headers are picked up
```
