### ISSUE TITLE
Add support for Sentry Metrics

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-react-native#3578]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including react-native

#### Open point:
How much of this can the react-native SDK inherit from the [JS SDK](https://github.com/getsentry/sentry-javascript/releases/tag/7.88.0)?

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

```[tasklist]
### Tasks
- [x] Re-export the metric APIs
- [x] Add an example to the sample applications
- [x] Code snippet to changelog
```

**Comment by krystofwoldrich** [comment]
I've tested the browser API in our Expo and RN sample apps, both send data to Sentry. So we only need to re-export the API in RN SDK.
