### ISSUE TITLE
Warn users when a white space is detected in source map path in Xcode builds

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3640]
### Description

React Native Xcode builds fail to generate source maps if a white space character is on the path to the source map,  https://github.com/facebook/react-native/issues/41652.

This can happen:
- because the project itself is on a patch with a white space
- SOURCEMAP_FILE was set to a path with white space
- Scheme name contains white space

This doesn't affect build without source maps, source maps are disabled by default. When developers add Sentry, which enables source maps, it looks like Sentry is causing the build to fail.

We can't fix the underlying issue, but we can warn our users about it when we detect the white space.

```[tasklist]
### Tasks
- [ ] Warn users about white space on the source map path
- [ ] If it's a schema name can we generate the source map elsewhere?
- [ ] Should we skip generating the source map to avoid failing the build?
``` 

- Related issue https://github.com/getsentry/sentry-react-native/issues/3583

**Comment by antonis** [comment]
Closing as the RN fix https://github.com/facebook/react-native/issues/41652 was merged in 0.74.x
