### ISSUE TITLE
Update NativeFrameInstrumentation to use `startSpan` event

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3702]
This change is required for JS v8, as`spanRecorder` was definitively removed.

- https://github.com/getsentry/sentry-javascript/pull/10977/

```[tasklist]
### Tasks
- [x] Add integration test not relying on internal structure NativeFramesInstrumention  [impl](https://github.com/getsentry/sentry-react-native/blob/071289ab6301baec9dc8f19d86e2779cc00e1902/src/js/tracing/nativeframes.ts#L24)
- [x] Replace `onTransactionStart` and `onTransactionFinish` by `client.on(spanStart)`
- [ ] Include NATIVE.* function in the instrumentation
- [x] Replace `instrumentChildSpanFinish` by `client.on(spanStart)`
```

Example tests: [timetodisplay.test.tsx](https://github.com/getsentry/sentry-react-native/blob/071289ab6301baec9dc8f19d86e2779cc00e1902/test/tracing/timetodisplay.test.tsx#L18), [reactnavigation.ttid.test.tsx](https://github.com/getsentry/sentry-react-native/blob/071289ab6301baec9dc8f19d86e2779cc00e1902/test/tracing/reactnavigation.ttid.test.tsx#L26)

**Comment by krystofwoldrich** [comment]
Done in https://github.com/getsentry/sentry-react-native/pull/3996
