### ISSUE TITLE
Build Expo sample app in CI

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3707]
### Description

Build Expo sample app in CI

```[tasklist]
### Tasks
- [x] Android (use expo prebuild) https://github.com/getsentry/sentry-react-native/pull/4361
- [x] iOS (use expo prebuild) https://github.com/getsentry/sentry-react-native/pull/4361
- [x] Web (use expo export -p web) https://github.com/getsentry/sentry-react-native/pull/4361
- [x] Expo Updates (use expo export) https://github.com/getsentry/sentry-react-native/pull/4458
```
