### ISSUE TITLE
RoutingInstrumentation stall tracking causes some reanimated animation to flicker

### ISSUE THREAD

**Issue by fdecampredon** [getsentry/sentry-react-native#3987]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.74.3

**Are you using Expo?**
- [ ]  Yes
- [ x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
const routingInstrumentation = new Sentry.RoutingInstrumentation();

Sentry.init({
  dsn: process.env.SENTRY_DSN,
  enabled: !__DEV__,
  environment: process.env.DEPLOYMENT_ENVIRONMENT,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
    }),
  ],
});
```
 
---
**I have the following issue:**
Some large animations using react-native-reanimated and involving animating padding, height and transform are flickering when sentry is enabled, setting `enableStallTracking` to `false` in `Sentry.ReactNativeTracing` options solves the issue.

**Steps to reproduce:**
It's unfortunately hard to create a minimal reproduction example. The bug only appears on complex animation involving height and or padding, I'll try later if I can isolate a more specific reproduction case.

**Actual result:** 
Those animations are flickering/jerking 

**Expected result:**
No interferences between reanimated and sentry

**Comment by krystofwoldrich** [comment]
@fdecampredon Thank you for the message, I understand that it's difficult to reproduce.

Could you share some example animation, where you are seeing the flicker, event if in new app it works it might help us debug the issue.

Does this affect animation driven by JS or by native or both? As disabling stall tracking helped I would assume the JS drive animations are affected.

**Comment by krystofwoldrich** [comment]
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.

**Comment by matinzd** [comment]
This is still happening and it's actively affecting users on production!

**Comment by matinzd** [comment]
After some digging the likely cause is setting a lot of setTimeouts inside the interation:

https://github.com/getsentry/sentry-react-native/blob/fe135918376819714679fec8bf2bb2e1f07ec64b/packages/core/src/js/tracing/integrations/stalltracking.ts#L113

It is scheduling running itself after 50 ms. Not sure how this can be optimized as it's above my pay grade.

**Comment by matinzd** [comment]
The issue is fixed in v6 with the new stall tracking integration:

https://github.com/getsentry/sentry-react-native/pull/3997
