### ISSUE TITLE
[EPIC] Feedback Widget for React Native

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#4302]
Sentry currently offers only Feedback API for React Native applications and the widget to collect feedback needs to be implemented by the app developers. The goal of this task is to provide pre-made widget, which can be directly used in React Native applications.

![](https://docs.sentry.io/mdx-images/user-feedback-widget-F3HHPXRV.png)

[Current browser widget docs.](https://docs.sentry.io/platforms/javascript/user-feedback/) 
[Current React Native Feedback api docs.](https://docs.sentry.io/platforms/react-native/user-feedback/)
[Example React Native implementation in Sentry Demo app](https://github.com/sentry-demos/sentry_react_native/pull/72)

### [Feature Branch /feedback-ui](https://github.com/getsentry/sentry-react-native/pull/4435)
- https://github.com/getsentry/sentry-react-native/pull/4435

### [Feature Branch /feedback-ui-2](https://github.com/getsentry/sentry-react-native/pull/4726)
 - https://github.com/getsentry/sentry-react-native/pull/4726

### Currently in progress for GA release
- [x] Support themes (light/dark mode) https://github.com/getsentry/sentry-react-native/pull/4677
- [x] Take screenshot button in the UI https://github.com/getsentry/sentry-react-native/pull/4714
- [x] Review Accessibility - VoiceOver (iOS) and TalkBack (Android) https://github.com/getsentry/sentry-react-native/issues/4302#issuecomment-2788927285
- [x] Add feedback widget to wizard (ask user if they would like to setup Feedback widget) https://github.com/getsentry/sentry-wizard/pull/969
- [x] Add Feedback Auto-Inject E2E test (maestro flow) https://github.com/getsentry/sentry-react-native/pull/4604

### Post GA Features
- [ ] https://github.com/getsentry/sentry-react-native/issues/4735
- [ ] https://github.com/getsentry/sentry-react-native/issues/4736
- [ ] #4737

### Done
- [x] https://github.com/getsentry/sentry-react-native/pull/4378
- [x] https://github.com/getsentry/sentry-docs/pull/12503
- [x] Fix Expo Web issues https://github.com/getsentry/sentry-react-native/pull/4558
- [x] https://github.com/getsentry/sentry-docs/pull/11980
- [x] https://github.com/getsentry/sentry-react-native/pull/4524
- [x] https://github.com/getsentry/sentry-react-native/issues/3859
- [x] https://github.com/getsentry/sentry-react-native/issues/4336
- [x] https://github.com/getsentry/sentry-react-native/issues/4337
- [x] https://github.com/getsentry/sentry-react-native/issues/4359
- [x] https://github.com/getsentry/sentry-react-native/pull/4328#issuecomment-2541865719
- [x] https://github.com/getsentry/sentry-react-native/issues/4356
- [x] https://github.com/getsentry/sentry-react-native/issues/4319
- [x] https://github.com/getsentry/sentry-react-native/pull/4483
- [x] fix: Disable movement/scroll only in overflow (iOS only issue)
- [x] feat: Add pull down to cancel https://github.com/getsentry/sentry-react-native/pull/4534
- [x] feat: [design] Add rounded corners and the appearance of a sheet with a darkened top
- [x] feat: Save form content when closed, failed (reopening the form keeps the content), only clear after sent https://github.com/getsentry/sentry-react-native/pull/4538
- [x] Show selected screenshot thumbnail/preview in the UI https://github.com/getsentry/sentry-react-native/pull/4545

**Comment by krystofwoldrich** [comment]
Example of: Disable movement/scroll only in overflow

https://github.com/user-attachments/assets/6bbb652b-3215-4c97-9769-05292e539a71

**Comment by krystofwoldrich** [comment]
Add rounded corners and the appearance of a sheet with a darkened top. See the example below.

Let's do this if possible just with styles.

<img width="429" alt="Image" src="https://github.com/user-attachments/assets/5f6fb9b3-943f-4357-8d38-2f81b2268d7a" />

**Comment by krystofwoldrich** [comment]
The two most popular libraries for image pickers in the RN ecosystem are https://www.npmjs.com/package/react-native-image-picker and https://www.npmjs.com/package/expo-image-picker.

Instead of guiding users on how to use the image picker libraries and how to hook them into the Sentry Feedback Widget, we could introduce a simpler interface, in which the Sentry Feedback Widget accepts the library object and calls it's APIs.

Example:

React Native Image Picker

```js
import * as ImagePicker from 'react-native-image-picker';

Sentry.init({
  integrations: [
    Sentry.feedbackIntegration({
      imagePicker: ImagePicker,
    }),
  ],
});
```

Expo Image Picker

```js
import * as ImagePicker from 'expo-image-picker';

Sentry.init({
  integrations: [
    Sentry.feedbackIntegration({
      imagePicker: ImagePicker,
    }),
  ],
});
```

**Comment by antonis** [comment]
Note: We also need to check if ([similar to iOS](https://github.com/getsentry/sentry-cocoa/pull/4801)) the permissions needed for accessing photos create complications.

**Comment by krystofwoldrich** [comment]
> Note: We also need to check if (https://github.com/getsentry/sentry-cocoa/pull/4801) the permissions needed for accessing photos create complications.

This is not an issue for the RN SDK, because we don't access any of the native API, but the image picker libraries we integrate with do.

**Comment by krystofwoldrich** [comment]
I noticed a small bug on Expo Web, where the image picker returns `data:`, `uri`.

It would be nice to support it on the Web, we can use the browser APIs to convert the base64 to UintArray, the rest of the form works perfectly.

<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/96fda75c-5fce-4de0-9827-09b0cf6d5774" />

**Comment by antonis** [comment]
>> Note: We also need to check if (https://github.com/getsentry/sentry-cocoa/pull/4801) the permissions needed for accessing photos create complications.
>
> This is not an issue for the RN SDK, because we don't access any of the native API, but the image picker libraries we integrate with do.

Makes sense 👍 Probably we can add a note in the documentation as a reminder on this.

> I noticed two bugs on Expo Web.

Thank you for reporting @krystofwoldrich 🙇 I'll iterate with a fix on those 🤞

**Comment by antonis** [comment]
Reopening to track down the tasks after the beta release.

**Comment by antonis** [comment]
## Review Accessibility
### TalkBack (Android) ✅ 

https://github.com/user-attachments/assets/1bf7dd9a-7c34-4c6e-929a-ddd0f770ab12

### VoiceOver (iOS) ⏭
