### ISSUE TITLE
Ensure Sentry is able to initialize without DSN if Spotlight is enabled

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#4372]
### Description

As part of the [requirement to make Spotlight compatible with SDKs](https://github.com/getsentry/spotlight/issues/545), the SDKs should be able to initialize without a DSN if Spotlight is enabled

```[tasklist]
### Blocked by
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4620
- [ ] https://github.com/getsentry/sentry-java/issues/3981
```

JS already supports this https://github.com/getsentry/sentry-javascript/blob/938fe65a1bb363bf92cb35df24edea27d3d75883/packages/core/src/baseclient.ts#L322

```[tasklist]
### Tasks
- [ ] Check if JS layer can send events to Spotlight without changes on native
```
